name: deployment pipelin

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Deploy to Cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: lEyYPCx1xmvVT9BbFfYnSqx_liawRf9-VVLwbHNA
          accountId: 3d6d8a46412c345c650d71c35464acc3
          projectName: discord-clone-frontend
          directory: .vercel/output/static
          branch: master
